mqtt:
  sensor:
    - name: "EET Solmate Online Status"
      state_topic: "eet-solmate/status/online"
    - name: "EET Solmate Power"
      state_topic: "eet-solmate/pv_power"
      unit_of_measurement: "W"
    - name: "EET Solmate Batterie Status"
      state_topic: "eet-solmate/battery_state"
      unit_of_measurement: "%"
    - name: "EET Solmate Batterie Flow"
      state_topic: "eet-solmate/battery_flow"
    - name: "EET Solmate Inject Power"
      state_topic: "eet-solmate/inject_power"
      unit_of_measurement: "W"
    - name: "EET Solmate Temperatur"
      state_topic: "eet-solmate/temperature"
      unit_of_measurement: "°C"
    - name: "EET Solmate Timestamp"
      state_topic: "eet-solmate/timestamp"
    - name: "EET Solmate MppOutI"
      state_topic: "eet-solmate/mppOutI"